name: CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Instal dependencies
        run: npm install

      - name: Build and zip extension artifact
        run: npm run package

      - name: Upload build artifact
        uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ./build/chrome-mv3-prod.zip
          retention-days: 1

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and zip extension artifact
        run: npm run package

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ./build/chrome-mv3-prod.zip

      # - name: Browser Platform Publish
      #   uses: PlasmoHQ/bpp@v3
      #   with:
      #     keys: ${{ secrets.SUBMIT_KEYS }}
      #     artifact: build/chrome-mv3-prod.zip
