name: CI

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Create .env with Plasmo public keys
        uses: PlasmoHQ/soft-secret@v1
        with:
          secret: ${{ secrets.PLASMO_PUBLIC_KEYS }}
          target: .env

      - name: Create and zip production build
        run: npm run build-zip

      - name: Upload build artifact
        uses: actions/upload-artifact@master
        with:
          name: fonts-jar
          path: ./build/chrome-mv3-prod.zip
          retention-days: 1
