name: Publish

on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Create .env with Plasmo public keys
        uses: PlasmoHQ/soft-secret@v1
        with:
          secret: ${{ secrets.PLASMO_PUBLIC_KEYS }}
          target: .env

      - name: Create and zip production build
        run: npm run build-zip

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1

      - name: Get version
        id: get-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          name: ${{ steps.get-version.outputs.current-version }}
          tag_name: ${{ steps.get-version.outputs.current-version }}
          draft: false
          prerelease: false
          files: build/chrome-mv3-prod.zip

      # - name: Browser Platform Publish
      #   uses: PlasmoHQ/bpp@v3
      #   with:
      #     keys: ${{ secrets.SUBMIT_KEYS }}
      #     artifact: build/chrome-mv3-prod.zip
